# Charless Plugin Configuration

# Message Configuration
messages:
  prefix: "&8[&bCharlesonia&8] &r"
  teleported: "&aTeleported to waypoint: %name%"
  player_only: "&cOnly players can use this command."
  operator_only: "&cOnly operators can use this command."
  invalid_item: "&cInvalid item: %item%"
  invalid_name: "&cInvalid waypoint name! Use only letters, numbers, and underscores (max 32 characters)." 

home:
  price: 1000 