name: homes
version: '1.0'
main: org.homes.homes.Main
api-version: '1.21'
load: STARTUP
commands:
  addhome:
    description: Add a home at your current location
    usage: /addhome <name>
  delhome:
    description: Delete a home or open the delete menu
    usage: /delhome <name>
  homes:
    description: Open the menu with your homes
    usage: /homes
  adminhome:
    description: Open the admin menu to manage all players' homes (OP only)
    usage: /adminhome
